### ISSUE TITLE
Script OS4Emu

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#10]
`Line 44: syntax error, unexpected ')' ')'`
http://aminet.net/package/misc/emu/OS4Emu_1.8

**Comment by sodero** [comment]
That script is broken. The appname is missing. From the Installer.guide:

The `startup' statement
------------------------------
 
(startup <**appname**> <parameters>)
 
This command edits the `S:User-Startup' file, which is executed by
the user's `Startup-Sequence' (Installer will modify the user's
`Startup-Sequence' if needed, although in a friendly way).  The
`command' parameter is used to declare AmigaDOS command lines which
will be executed.  The command lines are grouped by application, using
the supplied argument `appname'.  If there is already an entry in
`S:User-Startup' for that application, the new command lines will
completely replace the old.  The command lines for other applications
will not be affected.  Note:  The prompt and help parameters for the
`startup' statement are only used by the confirmation display to edit
`User-Startup'.  This only happens in NORMAL or EXPERT mode, or in
NOVICE mode if the `confirm' parameter is included.  Parameters:
 
`prompt'
`help'
      tell the user what's going to happen.
 
 `confirm'
      if this option is present, user will be prompted to confirm the
      operation, otherwise the modification proceeds silently.
 
 `command'
      used to declare an AmigaDOS command line to be executed at system
      startup.
 
 Note that Installer will try to locate the User-Startup file on the
 boot volume in the script directory. Only if this is not available, the
 assign `S:' will be used.

**Comment by sodero** [comment]
By the way, if you successfully run a script, please add it to the list in the Wiki, there's a 'status' page there where I try to keep track of things.

**Comment by polluks** [comment]
Are you sure? This works
````
; 

; Generated by InstallerGen 1.4!

(complete 0)
(set @default-dest "Work:")
````

**Comment by sodero** [comment]
Yes, the documentation is pretty clear on this point I think. But on the other hand, the CBM implementation doesn't always follow the documentation either (obviously). If more scripts use this 'feature' we need to come up with something. I assume that @app-name is used when the parameter is missing? But that's not good either, it can be empty, or undefined.

**Comment by polluks** [comment]
`Line 44: syntax error, unexpected ')' ')'`
BTW why do you repeat ')'?

**Comment by sodero** [comment]
It's because the token and the corresponding string are the same in this case (since the "string" is 1 byte long, refer to lexel.l line 62 and onwards for other examples). 

In other cases it could be something like 'unexpected SYM name_of_symbol' where SYM is the token and name_of_symbol is the string that is interpreted as SYM by the lexer.

The error messages from the parser could definitely be improved.

**Comment by polluks** [comment]
I see, it's a bit redundant right now.

**Comment by sodero** [comment]
I have a fix for this one. I changed my mind and made the parser more forgiving.
