### ISSUE TITLE
Abort window

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#13]
Its text should not "Proceed".
Maybe RC should be RETURN_WARN.

**Comment by sodero** [comment]
Can you attach an image? I'm 100% sure I'll fix the right button otherwise :)

**Comment by polluks** [comment]
Well, the button is ok but I found this:
`(abort @blabla)`
The window is closing immediately.

**Comment by sodero** [comment]
Yes, (abort @blabla) will exit directly unless @blabla is defined. If not, it will be interpreted as an empty string and empty messages aren't shown. I think it's unfortunate that the original installer allows this (undefined variables interpreted as "" or 0 depending on the context), but there are scripts that depend on this behaviour.

InstallerLG supports a stricter mode of execution that will catch things like this (and more). You can enable that with (set @strict 1) anywhere in your script.

A fix for the button is on its way.

**Comment by sodero** [comment]
Abort the RC; more needs to be done, see #12 .
