### ISSUE TITLE
Something goes wrong

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#31]
c:installer "/dist/InstallerLG installer"
`Line 73: Missing option 'default'`

**Comment by sodero** [comment]
Is 'c:installer' the default MorphOS installer or InstallerLG?

**Comment by polluks** [comment]
The second, it worked before.

**Comment by sodero** [comment]
Weird, I'll look into that. But I need to wait until I get home. I don't have my MorphOS machine at work :)

**Comment by sodero** [comment]
I slowly started the V44 work BTW. The way (trace), (retrace) and (back) works is slightly annoting, but we'll get there.

**Comment by sodero** [comment]
I'm afraid I can't reproduce this. From the latest build (top left from commandline, lower right from wb):

![installer_shot](https://user-images.githubusercontent.com/1541697/48794652-e1425500-ecfa-11e8-9390-85e3f241fe0b.png)

What version are you using?

**Comment by polluks** [comment]
Strange, it was ALPHA33 but Nov 13. However now it works.
BTW we have output of a single zero :)

**Comment by sodero** [comment]
Good! The zero will disappear later, it's just there for testing purposes.

**Comment by polluks** [comment]
I suppose I didn't make a `make clean` and mixed old and new objects.

**Comment by sodero** [comment]
Ah, that explains it. I added the V44 'back' token to the lexer so 'default' would no longer be 'default' then (due to 'b' being < 'd').
