### ISSUE TITLE
dist/InstallerLG installer

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#38]
Our script does not work anymore.
`make install` says "Line 84: No such file or directory 'Installer'"

**Comment by sodero** [comment]
Ah, I changed how the current directory is set upon start-up. Now
InstallerLG will change working directory to the directory of the script
before starting the interpreter from the command line as well (not just
from WB like before). I adapted the Makefile to make it work.

Br,
Ola

Den tis 17 sep. 2019 kl 00:35 skrev Stefan <notifications@github.com>:

**Comment by polluks** [comment]
Well, this is the behaviour of MorphOS' installer but CBM's doesn't change the directory.

**Comment by sodero** [comment]
I think the MorphOS installer does the right thing in this case. All the scripts I've seen so far depend upon being executed from their own directory. But if the CBM installer doesn't change directory then perhaps we shouldn't do it either. What do you think? Shall we go for 100% compatibility or for something that (we think) is better than the original?

**Comment by polluks** [comment]
@sodero It's ok if you write this in the guide.
