### ISSUE TITLE
makedir issues

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#40]
The trailing slash seems to make trouble...

**Comment by sodero** [comment]
Will look into it. Is this affecting both Roadshow and Deluxe music?

**Comment by sodero** [comment]
Roadshow is using (trap). Is that also the case with Deluxe music? That's just a stub in InstallerLG since it did not seem to work in the CBM installer. I need to look deeper into what the CBM installer (trap) statement does.

**Comment by polluks** [comment]
![dmcs](https://user-images.githubusercontent.com/4707573/67751553-9d3ef080-fa31-11e9-9511-e3027dbaf1b9.png)
Line 0?
[Install-DeluxeMusic.txt](https://github.com/sodero/InstallerLG/files/3782488/Install-DeluxeMusic.txt)

**Comment by sodero** [comment]
Line 0 is seriously broken. Thanks, will look into it.

**Comment by sodero** [comment]
Fixed.

**Comment by sodero** [comment]
Bah! It's leaking memory, crap.

**Comment by sodero** [comment]
Ok, silly misstake. Fixed now.

**Comment by polluks** [comment]
![dmcs2](https://user-images.githubusercontent.com/4707573/68388940-0c1ef680-0162-11ea-8ea5-4702682b8200.png)
Strange...

**Comment by sodero** [comment]
Wierd, are your file permissions OK?

**Comment by sodero** [comment]
Will try to reproduce it tonight.

**Comment by polluks** [comment]
BTW you see the German catalog because the system one (with the same name) is now ignored :)

**Comment by sodero** [comment]
I'm having trouble reproducing this on AROS (found a problem with CRLF / CR contaminated files though, because of me downloading the *.txt script above on Windows).

Does 'Applications' on DH3: exist before you run the script?
Is 'Applications' write-protected?
Does it make any difference if you change (makedir app_path (infos)) to just (makedir app_path)?

**Comment by polluks** [comment]
I also tried T:, no difference without (infos).

**Comment by sodero** [comment]
Ok, I'll test with MorphOS instead.

**Comment by polluks** [comment]
Thanks, however I see no fail with Snoopium...

**Comment by sodero** [comment]
I've struggled to reproduce this on MorphOS as well, but failed for some reason.

I did (makedir) more forgiving though. Maybe it works for you now?

If not, can you add (debug app_path) before (makedir) on line 302 and run from shell and see what the output is?

Can you also do a "list all" in DH3: to show all file / dir permissions?

**Comment by sodero** [comment]
BTW, when running Snoopy, did you tick all the checkboxes?

**Comment by polluks** [comment]
Finally it works!
