### ISSUE TITLE
ALPHA41 bug

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#41]
> Installer "InstallerLG installer"
Line 63: syntax error, unexpected ')' ')'

**Comment by sodero** [comment]
Are you sure that the "InstallerLG installer" script hasn't been corrupted in some way? I tried it on AROS, MorphOS and MacOS and everything seems fine.

**Comment by polluks** [comment]
`InstallerLG installer             6190 ----rw-d 29-Okt-19 00:05:30`
IDK
