### ISSUE TITLE
(delopts) as a function rather than an option to a function 

### ISSUE THREAD

**Issue by gareth-smyth** [sodero/InstallerLG#44]
The workbench 3.1 install disk uses "delopts" at the root level as follows...

```
(delopts "oknodelete" "force" "askuser")
```

InstallLG is unable to parse this as it only expects "delopts" as an option to functions.

I'm not sure if the installer _should_ allow this but since it's used in the official workbench install it seems like it should be handled in some way.

**Comment by gareth-smyth** [comment]
I'm happy to work on a fix if anyone has any ideas how this could be handled as there doesn't seem to be any way in the current lexer/parser to have both a function and an option with the same name.

**Comment by sodero** [comment]
Thanks for reporting this!

The CBM Installer is an endless pit of strange surprises.

About helping out; sure, that would be great. What is the effect when (delopts) is used at the root like above?

**Comment by gareth-smyth** [comment]
Running the script (on linux) returns
`Line 3410: syntax error, unexpected DELOPTS 'delopts'`

If I add a delopts test the error output is 
```
; In line 1
(delopts "a" "b" "c") ; [ ; ]
; Actual result [Line 1: syntax error, unexpected DELOPTS 'delopts']
; Expected result [abc]
```

**Comment by sodero** [comment]
Do you know what the CBM installer does in the WB install script? Are 'oknodelete', 'force' and 'askuser' deleted globally after the (delopts ...) statement or does it only apply to the next statement where these options exist?

**Comment by gareth-smyth** [comment]
It seems to do the opposite to what I would expect - it turns the option "on" in such a way that it cannot be turned off.  The following script creates 5 folders and sets the protection bit.  "tst2" is the only one which does not prompt the user to unprotect the folder before deleting it.

I can't find any way to turn off "askuser" after the delopts command.  "tst5" has it's own (delopts "askuser") but it still prompts.

The installer version i'm testing is from the "Install3.1" disk, it reports as `installer2 2.17 (13.2.93)`

```
(makedir "dh0:tst1")
(makedir "dh0:tst2")
(makedir "dh0:tst3")
(makedir "dh0:tst4")
(makedir "dh0:tst5")

(protect "dh0:tst1" "-d")
(protect "dh0:tst2" "-d")
(protect "dh0:tst3" "-d")
(protect "dh0:tst4" "-d")
(protect "dh0:tst5" "-d")

(delete "dh0:tst1" (optional "askuser"))            ; This prompts
(delete "dh0:tst2")                                 ; This doesn't prompt

(delopts "askuser")

(delete "dh0:tst3")                                 ; Prompts
(delete "dh0:tst4")                                 ; Prompts
(delete "dh0:tst5" (delopts "askuser"))             ; Prompts
```

**Comment by gareth-smyth** [comment]
It also seems like (delopts "askuser") as part of a command also sets it to "on" permanently so maybe I'm not understanding how delopts is supposed to work.

```
(makedir "dh0:tst1")
(makedir "dh0:tst2")
(makedir "dh0:tst3")

(protect "dh0:tst1" "-d")
(protect "dh0:tst2" "-d")
(protect "dh0:tst3" "-d")

(delete "dh0:tst1")                              ; No prompt
(delete "dh0:tst2" (delopts "askuser"))          ; Prompt
(delete "dh0:tst3")                              ; Prompt

```

**Comment by sodero** [comment]
Very good findings. It's really confusing and the Installer.guide is not very clear either.

I extended the parser so that options can be part a normal statement scope, in the root, if clauses and so on. Then I guess we 'just' have to figure out what (delopts) should do then :-)

**Comment by sodero** [comment]
By the way, about helping out: This particular problem is probably not the best starting point. It's quite difficult to solve without knowing the code base really well.

But I think that what you're doing in your fork is a great idea. It would be really nice to be able to use the installer from the console with a text-only user interface. If you'd like to I can make you a collaborator so that you can integrate your work and thereafter do all your changes in this repo.

**Comment by gareth-smyth** [comment]
Okay I'll leave this for now then.  I'll just finish my branch off and add some tests for it then I'll create a merge request if that suits.

**Comment by sodero** [comment]
I added you as a collaborator. You can push directly to a branch with a descriptive name of your choice.

**Comment by polluks** [comment]
@gareth-smyth You are welcome!

**Comment by sodero** [comment]
Fixed.
