### ISSUE TITLE
Requester in test case

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#49]
The system is looking for a volume called `_md_:`
https://github.com/sodero/InstallerLG/blob/600085b6984af015aa1a8a5a327e8efea64dbf08/test/test.makedir#L2

**Comment by sodero** [comment]
We could add a (makeassign "_md_" "t:") or something before (makedir) and then remove it afterwards with just (makeassign "_md_") after (if I remember correctly).

**Comment by polluks** [comment]
Okay, I did `assign _md_: ""` and everything was gone =D

**Comment by sodero** [comment]
I updated the test to make it work both on Amigoids and others.
