### ISSUE TITLE
Empty line in user-startup

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#51]
(set #startup-command (cat #startup-command "Path AmiSSL: ADD\n"))
...
````
Path AmiSSL: ADD

;END AmiSSL
````

**Comment by sodero** [comment]
Fixed.

**Comment by polluks** [comment]
Still the same...

**Comment by sodero** [comment]
Ok, I need to look into the rest of amissl installer

**Comment by polluks** [comment]
It also happend with vbcc.

**Comment by sodero** [comment]
I must be doing something wrong here. 

If I run this script using the latest commit on master:

(set @app-name "AmiSSL")

; BY SETTING THIS YOUR user-startup WON'T BE CLOBBERED
(set @user-startup "_st_")

(set #updateInstall 0)
(set #startup-command "")

; If assign missing (OS4 install) or new install
(if (or (= #updateInstall 0) (= #amissl-assign ""))
	(set #startup-command (cat "Assign AmiSSL: \"" #storage-dir "\"\n"))
)

(if (= #updateInstall 0)
	(set #startup-command
		(cat #startup-command
			"If Exists AmiSSL:Libs\n"
			"  Assign LIBS: AmiSSL:Libs ADD\n"
			"EndIf\n"
		)
	)
)

(if (= #updateInstall 0)
	(if	(askbool
			(prompt #str-add-path)
			(help #str-no-help)
			(default 1)
		)
		(set #startup-command (cat #startup-command "Path AmiSSL: ADD\n"))
	)
)

(if (<> #startup-command "")
	(startup @app-name
		(prompt #str-add-assign)
		(help @startup-help)
		(command #startup-command)
	)
)

Then '_st_' will contain this:

;BEGIN AmiSSL
Assign AmiSSL: ""
If Exists AmiSSL:Libs
  Assign LIBS: AmiSSL:Libs ADD
EndIf
Path AmiSSL: ADD
;END AmiSSL

Setting #updateInstall to 1 will give the same result.

**Comment by polluks** [comment]
[Please take a look](http://polluks.freeshell.org/download/51.lha)

**Comment by sodero** [comment]
Indeed, it happens with the build / script above. 

But if I use the same script with a gcc build from master it works. Could it be a build issue? I notice that your build is 16 bytes smaller than mine. I assume that your build is using gcc from the latest MorphOS SDK? Is it still the same size if you do a 'git pull', 'make clean' and 'make CC=gcc'?

**Comment by polluks** [comment]
Well, seems to be a gcc 9 bug! gcc 8 works fine.
Two months ago I switched to the new SDK from gcc 6. I suppose you can remove your changes again and avoid the niner.

**Comment by sodero** [comment]
Ah, nice. But I'll keep the changes anyway, because it is a real bug. Not very serious, but ugly. Another example of a strange feature of the original installer.
