### ISSUE TITLE
ASSERT w/ vbcc

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#61]
````
vc +aos68k -c99 -Ivbcc:PosixLib/include -Ivbcc:MUI/C/include -DMUIA_Dtpic_Name=0x80423d72 -I. -I../build -I../src -O -dontwarn=153 -DAMIGA -DLG_TEST   -c -o alloc.o alloc.c
>    ASSERT(src && dst)
error 273 in line 270 of "alloc.c": not enough arguments to macro
unexpected end of file
1 error found!
````
I don't know why the ellipsis of the macro is ignored...

**Comment by sodero** [comment]
Strange, is it only there or in all places where the third argument is left out?

**Comment by sodero** [comment]
Does ASSERT(src && dst , ) work BTW?

**Comment by sodero** [comment]
If so I guess we could do something like this:

In utils.h:
 90 #define VOID                                                                                                                                  
 91 #define ASSERT(S,R) if(!(S) && PANIC(NULL)) return R     

And then use ASSERT(src && dst, VOID) above...

**Comment by polluks** [comment]
This is the cause https://en.wikipedia.org/wiki/Variadic_macro#Trailing_comma

**Comment by sodero** [comment]
Ah, seems like I assumed that gcc == iso c. I'll change that so that we use VOID instead of varargs.

**Comment by polluks** [comment]
Indeed, we should use -pedantic
https://stackoverflow.com/questions/38939991/how-to-disable-gnu-c-extensions

**Comment by sodero** [comment]
Good idea, that would have saved us from the VBCC build problem from the start. Fixed it.

**Comment by polluks** [comment]
````
gcc -I . -I ../src -Os -std=gnu99 -DAMIGA -noixemul -Wall -Wextra -Werror -pedantic -Wno-pointer-sign -D__AMIGADATE__="\"(24.07.2020)\""
 -c -o alloc.o ../src/alloc.c
In file included from ../src/alloc.c:14:
../src/util.h:90: error: "VOID" redefined [-Werror]
   90 | #define VOID
      |
In file included from /New_Work/Development/gg/os-include/clib/debug_protos.h:11,
                 from ../src/util.h:20,
                 from ../src/alloc.c:14:
/New_Work/Development/gg/os-include/exec/types.h:18: note: this is the location of the previous definition
   18 | #define VOID        void
      |
cc1: all warnings being treated as errors
````

**Comment by sodero** [comment]
Oh, namespace problems. Changed ASSERT->LG_ASSERT and VOID->LG_VOID. Should be better.
