### ISSUE TITLE
Port installerLG to AmigaOS4

### ISSUE THREAD

**Issue by samo79** [sodero/InstallerLG#65]
Would be nice to have InstallerLG ported to AmigaOS4

**Comment by sodero** [comment]
Yes, that's my plan. I've paused this one for a couple of months while working on gcc for OS4 but my plan is to start working again on InstallerLG very soon and an OS4 version is a part of that.

**Comment by sodero** [comment]
Done: https://github.com/sodero/InstallerLG/releases/tag/1.0.2
