### ISSUE TITLE
@default-dest of SDL2

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#66]
Why the default "T:"?
![our](https://user-images.githubusercontent.com/4707573/118797033-af8ab480-b88b-11eb-888f-b5f83add2185.png)
![other](https://user-images.githubusercontent.com/4707573/118797070-b87b8600-b88b-11eb-8f66-880ca57cd10a.png)

**Comment by sodero** [comment]
Thanks, I'll have a look

**Comment by sodero** [comment]
The CBM Installer initializes @default-dest to "Work:", so I'll do the same. The CBM Installer is the target after all, not the MorphOS installer.
