### ISSUE TITLE
Tooltype APPBANNER

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#67]
See [SDL2](https://www.morphos-storage.net/dl.php?id=1613254)
https://user-images.githubusercontent.com/4707573/118797070-b87b8600-b88b-11eb-8f66-880ca57cd10a.png

**Comment by sodero** [comment]
Should be doable. I just need to get some time, been struggling a lot with that lately.

**Comment by sodero** [comment]
Fixed.
