### ISSUE TITLE
Huge bubble without line breaks

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#69]
![bubble](https://user-images.githubusercontent.com/4707573/123699366-7c125100-d85f-11eb-9d3b-918101203653.png)
We need our own word wrap because the line will be truncated.

**Comment by sodero** [comment]
It seems that MUI doesn't like help texts ending with newlines, see below. Newlines in other places are OK. Could be a MUI bug. I'll see if Aros / Zune behaves in the same way.

![works](https://user-images.githubusercontent.com/1541697/124367938-405ef900-dc5c-11eb-9f06-711d40abd3a3.png)
![broken](https://user-images.githubusercontent.com/1541697/124367951-579de680-dc5c-11eb-941d-fd4dc6473b93.png)

**Comment by sodero** [comment]
Ok, Zune works slightly different. It doesn't wrap at all, but it can handle strings that end with a newline. I guess we need to implement a custom wrapper / chomper depending on OS. A bit cumbersome but I guess there's no way around it. I'll fix it.

**Comment by sodero** [comment]
Or we simply skip using the builtin wrapper on MorphOS and always wrap and strip ending newlines always, no matter what OS we're using.
