### ISSUE TITLE
Return Code on script error

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#7]
````
Line 1: syntax error, unexpected RUN, expecting '(' 'run'
RC=0
````

**Comment by sodero** [comment]
Where can I find this script?

**Comment by polluks** [comment]
Just any nonsense script like run.sh
BTW there's no source in InstallerLG.src.lha

**Comment by polluks** [comment]
The messages are fine. I was talking about a DOS RETURN_OK if the script has an error.

**Comment by sodero** [comment]
Ok, I'll fix that.

**Comment by sodero** [comment]
So if the script is broken you would like the return value to be RETURN_OK? Or RETURN_ERROR? I don't have access to UAE from here I'm afraid. Do you know how the CBM implementation behaves?

#define RETURN_OK			    0  /* No problems, success */
#define RETURN_WARN			    5  /* A warning only */
#define RETURN_ERROR			   10  /* Something wrong */
#define RETURN_FAIL			   20  /* Complete or severe failure*/

**Comment by sodero** [comment]
Syntax error -> RETURN_ERROR
File not found / readable -> RETURN_FAIL

**Comment by polluks** [comment]
The CBM Installer sets no RC at all which is not style guide conform. My suggestions:
````
#define RETURN_OK	 0 /* No problems, success */
#define RETURN_WARN	 5 /* User abort */
#define RETURN_ERROR	 10 /* Script error */
#define RETURN_FAIL	 20 /* InstallerLG failure */
````

**Comment by polluks** [comment]
File not found / readable -> RETURN_ERROR + 1
