### ISSUE TITLE
Installer of SDL_2.0.20_Libraries.lha

### ISSUE THREAD

**Issue by polluks** [sodero/InstallerLG#70]
`(set #morphos (getversion "MORPHOS" (resident) ))` returns 0

**Comment by sodero** [comment]
That's a strange way of doing it. What is MORPHOS in this case? Installers typically use version.library to check OS version, that's what it's for. Is it used to detect whether we're executing on MOS or to get the actual version of MOS?

**Comment by polluks** [comment]
Both, `version morphos` is a valid shell command.

**Comment by sodero** [comment]
Thanks, will look into it

**Comment by sodero** [comment]
Closed in 200199d790612c7ce83004c78a877c890f06acc2
